// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBkT2eDwKO5E1vr58Gt8CV3RJQhJoUoilk',
    appId: '1:257791458072:web:d884a41283408c3d67fc6d',
    messagingSenderId: '257791458072',
    projectId: 'communitypagereal',
    authDomain: 'communitypagereal.firebaseapp.com',
    storageBucket: 'communitypagereal.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGPqqDdrYilYZc94-ge6iMrxZgJMrI6WE',
    appId: '1:257791458072:android:bb3256f786a8636b67fc6d',
    messagingSenderId: '257791458072',
    projectId: 'communitypagereal',
    storageBucket: 'communitypagereal.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB638TnNFMt_betioSmilgJ_KvWBBOTUrg',
    appId: '1:257791458072:ios:542b66775b4c134267fc6d',
    messagingSenderId: '257791458072',
    projectId: 'communitypagereal',
    storageBucket: 'communitypagereal.appspot.com',
    iosBundleId: 'com.example.handichatcraftW1956102Communitypage',
  );
}
