// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQWBJlVGCRlqiIYYER37gh4ssPmZLcIBY',
    appId: '1:339966306380:web:fc5912ec795912ad272ce9',
    messagingSenderId: '339966306380',
    projectId: 'signin-signup-4c0e6',
    authDomain: 'signin-signup-4c0e6.firebaseapp.com',
    storageBucket: 'signin-signup-4c0e6.appspot.com',
    measurementId: 'G-ZFJGXQ19PS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0QN-sggU_TNk0x50o54ZmUPrewmc9Nps',
    appId: '1:339966306380:android:005b6204952aa1de272ce9',
    messagingSenderId: '339966306380',
    projectId: 'signin-signup-4c0e6',
    storageBucket: 'signin-signup-4c0e6.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBAAFJkw_NAKxryxbBg3buU2DcaBV4QPJU',
    appId: '1:339966306380:ios:4badb096238cce3d272ce9',
    messagingSenderId: '339966306380',
    projectId: 'signin-signup-4c0e6',
    storageBucket: 'signin-signup-4c0e6.appspot.com',
    iosBundleId: 'com.example.handichatcraftW1986581',
  );
}
