// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA95g5K_7leHokz9SJHH3RoVv354g44BSY',
    appId: '1:228341241320:web:2d2a4d956cec4955ea405d',
    messagingSenderId: '228341241320',
    projectId: 'handichatcraft-a195d',
    authDomain: 'handichatcraft-a195d.firebaseapp.com',
    storageBucket: 'handichatcraft-a195d.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFikb1DHO5lckAGkLbofFAFvBpWQBMA-w',
    appId: '1:228341241320:android:21988df253adaae9ea405d',
    messagingSenderId: '228341241320',
    projectId: 'handichatcraft-a195d',
    storageBucket: 'handichatcraft-a195d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASXwQbwyukn7m-mRRJBywSV0J_49JTjnM',
    appId: '1:228341241320:ios:81b2fbad13dcf837ea405d',
    messagingSenderId: '228341241320',
    projectId: 'handichatcraft-a195d',
    storageBucket: 'handichatcraft-a195d.appspot.com',
    iosBundleId: 'com.example.handichatcraftW1985612',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASXwQbwyukn7m-mRRJBywSV0J_49JTjnM',
    appId: '1:228341241320:ios:9ae444bac4656351ea405d',
    messagingSenderId: '228341241320',
    projectId: 'handichatcraft-a195d',
    storageBucket: 'handichatcraft-a195d.appspot.com',
    iosBundleId: 'com.example.handichatcraftW1985612.RunnerTests',
  );
}
