// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web; 
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCf4_k5-TnrIXaiBBdGNGXYeMS-7P1oOv4',
    appId: '1:169795000595:web:6510656d813397dfbb62e6',
    messagingSenderId: '169795000595',
    projectId: 'notifications-fc763',
    authDomain: 'notifications-fc763.firebaseapp.com',
    storageBucket: 'notifications-fc763.appspot.com',
    measurementId: 'G-80CXX68ZT7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA_4MJK1Qlsa96LW7fAvdqTD3vPOJz51ko',
    appId: '1:169795000595:android:6a8d912029f933e0bb62e6',
    messagingSenderId: '169795000595',
    projectId: 'notifications-fc763',
    storageBucket: 'notifications-fc763.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_GMr2Vz03tDBupCeBUClm0oU6h2vXA4o',
    appId: '1:169795000595:ios:2e1a522c1b73784bbb62e6',
    messagingSenderId: '169795000595',
    projectId: 'notifications-fc763',
    storageBucket: 'notifications-fc763.appspot.com',
    iosBundleId: 'com.google.firebase.presents.pushNotifications',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_GMr2Vz03tDBupCeBUClm0oU6h2vXA4o',
    appId: '1:169795000595:ios:1e54e25a2dacba68bb62e6',
    messagingSenderId: '169795000595',
    projectId: 'notifications-fc763',
    storageBucket: 'notifications-fc763.appspot.com',
    iosBundleId: 'com.google.firebase.presents.pushNotifications.RunnerTests',
  );
}
