// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA22CjZFoSZ0H21o9XsC0UwAyBQz0meFDU',
    appId: '1:853942530418:web:6bc5970df3906fa8062deb',
    messagingSenderId: '853942530418',
    projectId: 'push-notifications-real',
    authDomain: 'push-notifications-real.firebaseapp.com',
    storageBucket: 'push-notifications-real.appspot.com',
    measurementId: 'G-6D8XBJS5KL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC25pqqQZ9j29JvODsu6Wem4ekIrchteVM',
    appId: '1:853942530418:android:5cfebeb5a44a00c5062deb',
    messagingSenderId: '853942530418',
    projectId: 'push-notifications-real',
    storageBucket: 'push-notifications-real.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAlt3GsEnLiSemYEoF9Ia_R3nYBmCsfTyo',
    appId: '1:853942530418:ios:a8709170b9b45fc0062deb',
    messagingSenderId: '853942530418',
    projectId: 'push-notifications-real',
    storageBucket: 'push-notifications-real.appspot.com',
    iosBundleId: 'com.example.pushnotificationreal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAlt3GsEnLiSemYEoF9Ia_R3nYBmCsfTyo',
    appId: '1:853942530418:ios:7d97b2e3293e290c062deb',
    messagingSenderId: '853942530418',
    projectId: 'push-notifications-real',
    storageBucket: 'push-notifications-real.appspot.com',
    iosBundleId: 'com.example.pushnotificationreal.RunnerTests',
  );
}
